# Generated by Django 5.0.6 on 2024-06-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=40)),
                ("region", models.CharField(max_length=20, verbose_name="Region:")),
                ("province", models.CharField(max_length=20, verbose_name="Province:")),
                ("district", models.CharField(max_length=20, verbose_name="District:")),
                ("village", models.CharField(max_length=30, verbose_name="Village:")),
                (
                    "doc",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Create Date:"
                    ),
                ),
                (
                    "dou",
                    models.DateTimeField(auto_now=True, verbose_name="Update Date:"),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
    ]
